# Generated by Django 6.0.7 on 2026-08-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name, e.g. 'Reception PC'", max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='e.g. 192.168.1.25', unique=True)),
                ('mac_address', models.CharField(blank=True, help_text='e.g. AA:BB:CC:DD:EE:FF (optional, auto-detected via ARP when possible)', max_length=17)),
                ('location', models.CharField(blank=True, help_text="e.g. 'Office - Floor 2'", max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_up', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_response_ms', models.FloatField(blank=True, null=True)),
                ('last_seen_up', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
