# Generated by Django 6.0.7 on 2026-08-03 18:13

from django.db import migrations, models
import django.db.models.deletion


DEPARTMENTS = [
    "Engineering",
    "Billing",
    "Mailing",
    "Post-office",
    "Reception",
    "Directors",
    "Inward",
    "Business",
    "Company-secretory",
    "Evoting",
    "Corporate-action",
    "Addmission",
    "Dividend",
    "Depository-particepant",
    "Demat",
]


def seed_departments(apps, schema_editor):
    Department = apps.get_model("devices", "Department")
    for name in DEPARTMENTS:
        Department.objects.get_or_create(name=name)


def unseed_departments(apps, schema_editor):
    Department = apps.get_model("devices", "Department")
    Department.objects.filter(name__in=DEPARTMENTS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="device",
            name="port",
            field=models.CharField(blank=True, help_text="e.g. switch port 'Gi0/12' or '24'", max_length=50),
        ),
        migrations.AddField(
            model_name="device",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="devices.department",
            ),
        ),
        migrations.RunPython(seed_departments, unseed_departments),
    ]
