# Generated by Django 6.0.7 on 2026-08-12 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='check_port',
            field=models.PositiveIntegerField(blank=True, help_text='Optional TCP port for up/down when ping is blocked (e.g. 445, 22, 3389, 80)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
