# Generated by Django 6.0.7 on 2026-08-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port_from',
            field=models.CharField(blank=True, help_text='First port on this switch, e.g. D-1', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='port_to',
            field=models.CharField(blank=True, help_text='Last port on this switch, e.g. D-20', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('pc', 'PC'), ('printer', 'Printer'), ('centralized', 'Centralized'), ('access_point', 'Access Point'), ('switch', 'Switch')], db_index=True, default='pc', help_text='Device type: PC, Printer, Centralized, Access Point, Switch', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='employee',
            field=models.CharField(help_text='Employee name, or switch name (e.g. Switch-1)', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='e.g. 192.168.1.25 (leave empty for unmanaged switches)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.CharField(blank=True, help_text="Desk/switch port, e.g. D-1 (must fall in a switch's range)", max_length=50),
        ),
    ]
